# Generated by Django 5.2 on 2025-04-25 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_description_alter_course_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('start_date', models.DateTimeField(verbose_name='Startzeit')),
                ('end_date', models.DateTimeField(verbose_name='Endzeit')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Kurs', to='courses.course', verbose_name='Kurs')),
            ],
        ),
    ]
