services:
  studurizer:
    build:
      context: .
    image: studurizer
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data/ # Path to db, change left path
      - ./media:/app/media # Path to media folder, change left path
    environment:
      - SECRET_KEY=${SECRET_KEY:-default_development_key}
