services:
  studurizer:
    container_name: studurizer
    image: ghcr.io/johann110/studurizer-fallstudie-software-engineering:latest
    ports:
      - "80:80"  # Exponiert Port 80
    volumes:
      - ./data:/app/data # Pfad zur lokalen SQLite-Datenbank (links anpassen, falls nötig)
      - ./media:/app/media            # Ordner für Medien-Dateien (links anpassen, falls nötig)
    environment:
      - SECRET_KEY=${SECRET_KEY:-default_development_key}  # SECRET_KEY generieren: https://djecrety.ir oder z. B. python -c "import secrets; print(secrets.token_urlsafe(50))"
#      - DOMAIN=${DOMAIN:-DOMAIN} # Domain setzen wenn SSL benutzt wird oder eine Domain um auf die App zugreifen (optional)
#      E-Mails sind optional, diese werden genutzt um E-Mails an Nutzer zu senden (z.B. Zertifikate oder Informationen)
#      - SMTP_USERNAME=user@gmail.com # Username für den SMTP Server
#      - SMTP_PASSWORD=myappassword     # SMTP Passwort
#      - SMTP_SERVER=smtp.gmail.com         # SMTP Server
#      - SMTP_PORT=587                      # SMTP Port
#      - SMTP_DOMAIN=gmail.com              # Domäne der E-Mail Domain @domain.com
#      - USE_SSL=False                      # SSL benutzen wenn StarTLS nicht geht / Default: False
#      - USE_STARTLS=True                   # StarTLS benutzen / Default: True