# Generated by Django 5.2 on 2025-04-10 17:29

import django.core.validators
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('file', models.FileField(help_text='The document file', upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'zip', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('doc_type', models.CharField(choices=[('lecture', 'Lecture Notes'), ('assignment', 'Assignment'), ('resource', 'Additional Resource'), ('syllabus', 'Syllabus'), ('other', 'Other')], default='resource', help_text='Type of document', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of upload')),
                ('is_public', models.BooleanField(default=True, help_text='Whether the document is visible to all course participants')),
                ('course', models.ForeignKey(help_text='Course this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='courses.course')),
                ('session', models.ForeignKey(blank=True, help_text='Session this document is related to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='courses.session')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this document', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
