# Generated by Django 5.2 on 2025-04-10 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Course title', max_length=255)),
                ('code', models.CharField(help_text='Unique course code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Course description')),
                ('start_date', models.DateField(help_text='Course start date')),
                ('end_date', models.DateField(help_text='Course end date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the course is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(help_text='Course teacher', on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, help_text='Date of enrollment')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the enrollment is active')),
                ('course', models.ForeignKey(help_text='Course enrolled in', on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(help_text='Enrolled student', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(help_text='Students enrolled in the course', related_name='enrolled_courses', through='courses.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Session title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Session description')),
                ('date', models.DateField(help_text='Session date')),
                ('start_time', models.TimeField(help_text='Session start time')),
                ('end_time', models.TimeField(help_text='Session end time')),
                ('location', models.CharField(blank=True, help_text='Session location (if applicable)', max_length=255)),
                ('is_online', models.BooleanField(default=False, help_text='Whether this is an online session')),
                ('online_meeting_link', models.URLField(blank=True, help_text='Link to online meeting (if applicable)', null=True)),
                ('course', models.ForeignKey(help_text='Course this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
