name: Build, Test and Push

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Normalize image name (lowercase)
        run: echo "IMAGE_NAME_LOWER=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set Docker tag
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            echo "DOCKER_TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build Docker Image for Testing
        run: docker compose build

      - name: Ensure database file exists
        run: touch db.sqlite3

      - name: Start container with Docker Compose
        run: |
          docker compose up -d
          sleep 10

      - name: Test server availability on port 8000
        run: |
          if curl -sSf http://localhost:8000/ > /dev/null; then
            echo "✅ Server is reachable on port 8000"
          else
            echo "❌ Server is not reachable on port 8000"
            docker compose logs
            exit 1
          fi

      - name: Run Django tests
        run: docker compose exec -T studurizer python manage.py test

      - name: Show logs if tests failed
        if: ${{ failure() }}
        run: docker compose logs

      - name: Stop container
        if: always()
        run: docker compose down

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME_LOWER }}:${{ env.DOCKER_TAG }}